/*
 * This file is auto-generated by scripts/generate-app-env.js.
 * Do not edit manually.
 */

export type GeneratedAppEnv = {
  apiBaseUrl: string | null;
  apiPort: string | null;
  mapboxPublicToken: string | null;
  sensorWsUrl: string | null;
  wsBaseUrl: string | null;
};

export const APP_ENV: GeneratedAppEnv = {
  apiBaseUrl: "https://macradar.onrender.com",
  apiPort: "8090",
  mapboxPublicToken: "pk.eyJ1IjoibWFjcmFkYXIiLCJhIjoiY2x0ZXN0MTIzIn0.test_token_placeholder",
  sensorWsUrl: "wss://macradar-rust-sensor.onrender.com/ws/sensors",
  wsBaseUrl: "wss://macradar.onrender.com",
};
