export const TRACKING_CONFIG = {
  heartbeatIntervalMs: 700,
  interpolationBackTimeMs: 70,
  localBlendFactor: 0.62,
  maxExtrapolationMs: 240,
  maxPredictionDriftMeters: 2,
  minHeadingDeltaDeg: 3,
  minPublishDistanceMeters: 0.06,
  minPublishIntervalMs: 40,
  minRenderDistanceMeters: 0.015,
  minRenderHeadingDeltaDeg: 1.5,
  minMotionEnergyDelta: 0.03,
  minSpeedDeltaMps: 0.08,
  motionPredictionWindowMs: 700,
  remoteAnimationFrameMs: 16,
  remotePlayerTtlMs: 5000,
  reconnectBaseDelayMs: 350,
  reconnectMaxDelayMs: 2500,
  sensorIntervalMs: 33,
  staleGpsFallbackSpeedMps: 0.65,
} as const;
