const fs = require('node:fs');
const path = require('node:path');

const ROOT_DIR = path.resolve(__dirname, '..');
const ENV_FILE = path.join(ROOT_DIR, '.env');
const OUTPUT_FILE = path.join(ROOT_DIR, 'src', 'config', 'appEnv.generated.ts');

function parseEnvFile(raw) {
  const output = {};
  const lines = raw.split(/\r?\n/);

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) {
      continue;
    }

    const delimiterIndex = trimmed.indexOf('=');
    if (delimiterIndex <= 0) {
      continue;
    }

    const key = trimmed.slice(0, delimiterIndex).trim();
    let value = trimmed.slice(delimiterIndex + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }

    output[key] = value;
  }

  return output;
}

function readEnvFile() {
  if (!fs.existsSync(ENV_FILE)) {
    return {};
  }

  try {
    const raw = fs.readFileSync(ENV_FILE, 'utf8');
    return parseEnvFile(raw);
  } catch {
    return {};
  }
}

function normalize(value) {
  if (typeof value !== 'string') {
    return null;
  }

  const trimmed = value.trim();
  return trimmed.length > 0 ? trimmed : null;
}

function resolveEnvValue(envFromFile, key) {
  if (typeof process.env[key] === 'string') {
    return normalize(process.env[key]);
  }
  return normalize(envFromFile[key]);
}

function buildOutput(payload) {
  return `/*\n * This file is auto-generated by scripts/generate-app-env.js.\n * Do not edit manually.\n */\n\nexport type GeneratedAppEnv = {\n  apiBaseUrl: string | null;\n  apiPort: string | null;\n  mapboxPublicToken: string | null;\n  wsBaseUrl: string | null;\n};\n\nexport const APP_ENV: GeneratedAppEnv = {\n  apiBaseUrl: ${JSON.stringify(payload.apiBaseUrl)},\n  apiPort: ${JSON.stringify(payload.apiPort)},\n  mapboxPublicToken: ${JSON.stringify(payload.mapboxPublicToken)},\n  wsBaseUrl: ${JSON.stringify(payload.wsBaseUrl)},\n};\n`;
}

function main() {
  const envFromFile = readEnvFile();
  const payload = {
    apiBaseUrl: resolveEnvValue(envFromFile, 'MACRADAR_API_BASE_URL'),
    apiPort: resolveEnvValue(envFromFile, 'MACRADAR_API_PORT'),
    mapboxPublicToken: resolveEnvValue(
      envFromFile,
      'MACRADAR_MAPBOX_PUBLIC_TOKEN',
    ),
    wsBaseUrl: resolveEnvValue(envFromFile, 'MACRADAR_WS_BASE_URL'),
  };

  fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true });
  fs.writeFileSync(OUTPUT_FILE, buildOutput(payload), 'utf8');
  const relativePath = path.relative(ROOT_DIR, OUTPUT_FILE);
  console.log(`[env] generated ${relativePath}`);
}

main();
